# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 334aa4a691a171913e118594fe8714b0c1cae2a60ab68f01f536e384b098275b5a9c3ee59321d6ff97a77752ca1c8ed290b908b65bc698fd03fec12d98700c51

test:
  secret_key_base: 0f189085eeea96e692c157e436f175418736ccc183f50720a5bd05ff2eec41bbc51108508a195e409d0d3032d707bccefc664b35e70a9eee381e463c82983a7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
